version: '3.5'
networks:
  component-tests:
    external: true
    name: component-tests-${BUILD_ID}

services:
  simple-jwt-provider:
    build:
      context: .
    restart: on-failure
    environment:
      SJP_JWT_PRIVATE_KEY: "\n-----BEGIN EC PRIVATE KEY-----\nMIHcAgEBBEIASzDZeTVLxcE5KTAmwrKwFjzr5cDrA+tttx9XRUz0K7AlROtj7cMG\nrHu/bdKj7lc2WaW8x/EOrU/FeCcsIL5nTH+gBwYFK4EEACOhgYkDgYYABAFBJr90\nWldGrPppBCbHqw2nGXeafxnSj6qB+A7E8A/G74mmmwIaqtf/pJ5QjqTPcAVUAEYF\nTz/0SPO3tPL1Ym3V0QH7TfnTf7EueabJqPdsSGR6uvbb2YOA9vy4OU8SXp/9a/4x\nr94giWgKjxYkB7xiy+IiZsWEBXU0rz7rb+IwJ82PfQ==\n-----END EC PRIVATE KEY-----"
      SJP_JWT_AUDIENCE: "<audience>"
      SJP_JWT_ISSUER: "<issuer>"
      SJP_JWT_SUBJECT: "<subject>"
      SJP_DSN: "host=db user=postgres password=postgres dbname=simple-jwt-provider port=5432 sslmode=disable"
      SJP_ADMIN_API_ENABLE: "true"
      SJP_ADMIN_API_USERNAME: "username"
      # escape $ with $
      SJP_ADMIN_API_PASSWORD: "bcrypt:$$2y$$12$$eOiNiEyREa2viPff8suTR.vw.HZSOSLGZE2ozfonFRn6w4HkV4Dbe"
      SJP_MAIL_SMTP_HOST: "mail-server"
      SJP_MAIL_SMTP_PORT: 1025
      SJP_MAIL_SMTP_PASSWORD: ""
      SJP_MAIL_SMTP_USERNAME: ""
      SJP_MAIL_TLS_INSECURE_SKIP_VERIFY: "true"
      SJP_MAIL_TLS_SERVER_NAME: "mail-server"
    networks:
      - component-tests

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "simple-jwt-provider"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    networks:
      - component-tests

  mail-server:
    image: mailhog/mailhog
    restart: always
    networks:
      - component-tests