@startuml
actor User as u
participant "simple-jwt-provider" as sjp
participant "mail-server" as ms
participant "mail-client" as mc

u -> sjp: trigger password-reset request
sjp->sjp: generate password-reset mail
sjp->ms: send password-reset mail with reset token
ms->mc: receive password-reset mail
mc->u: receive password-reset mail and extract reset-token

u->sjp: reset password with received token

@enduml
